id: IA506BC01
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:37:46+00:00'
last_modified: '2022-06-07T14:54:14.103372+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC339
  title: 《密宗道次第心要》讲授--贡噶活佛
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B6D:
      image_group_id: I4PD4482
      title: ''
      total_pages: 364
      order: 1
      base_file: 9B6D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
